#! /bin/bash
install:
	sudo apt-get upgrade -y
	sudo apt-get install python3-pip -y
	sudo apt-get install unzip -y
	sudo apt-get install -y chromium-browser
	sudo apt-get install -y chromium-chromedriver
	pip3 install selenium
	export PATH=$PATH:/usr/lib/chromium-browser/